import './globals.css';
import Link from 'next/link';
import ProtectedWrapper from '@/components/ProtectedWrapper';
import LogoutButton from '@/components/LogoutButton';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="h-16 bg-[#1F2937]">
          <div className="h-full container-auto px-6 flex justify-between items-center">
            <Link
              href={'/'}
              className="font-poppins font-semibold text-2xl text-white tracking-wide"
            >
              blog.
            </Link>
            <ProtectedWrapper
              ifHasUser={<LogoutButton />}
              ifNoUser={
                <Link
                  href={'/login'}
                  className="inline-block rounded-md border border-blue-600 bg-blue-600 px-4 py-2 text-sm font-bold text-white transition hover:bg-transparent hover:text-blue-600 focus:outline-none focus:ring active:text-blue-500"
                >
                  Login
                </Link>
              }
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
